language: python
sudo: required
dist: trusty
install:
    - |
        travis_mysql_ping() {
             local i
             until (( i++ > 10 )) || mysql <<<'select 1;'; do sleep 1; done
        }
    - sudo service mysql stop
    - travis_mysql_ping &
script: sudo service mysql start
notifications:
    email: never
