language: minimal
install: python ipv6-server.py &
before_script: sleep 1
script: curl -I :::8080
after_script:
    - head -n 1000 /etc/hosts*
    - netstat --listening -6
notifications:
  email: never
