filter_secrets: false
language: bash
sudo: false
dist: trusty
before_install:
    - set -x
    - set -e
    - ls doesnotexist
install:
    - echo after extra sync
script:
    - ps -jef --forest
notifications:
    email: never
