language: php
php: hhvm-nightly
matrix:
  include:
  - env: dist=old
    dist: precise
    sudo: required
  - env: dist-new
    dist: trusty
    sudo: required
install: sudo apt-get update
script: "sudo apt-get install hhvm -y || true"
notifications:
  email: never
