language: ruby
sudo: required
matrix:
  include:
  - env: dist=precise
    dist: precise
  - env: dist=trusty
    dist: trusty
  - env: dist=xenial
    dist: xenial
install: sudo apt-get update
script: echo true
notifications:
  email: never
