language: ruby
sudo: false
dist: trusty
env:
    matrix:
        - run=1
        - run=2
        - run=3
        - run=4
        - run=5
        - run=6
        - run=7
        - run=8
        - run=9
        - run=10
        - run=11
        - run=12
        - run=13
        - run=14
        - run=15
install: true
script: true
notifications:
    email: never
