language: ruby
addons:
  apt:
    packages:
    - moreutils
script: true
matrix:
    include:
        - env: fix=no-ec2
          sudo: false
        - env: fix=no-gce
          sudo: required
        - env: fix=no-gce
          sudo: required
          group: deprecated-2017Q4
install: true
notifications:
    email: never
