language: ruby
addons:
  apt:
    packages:
    - moreutils
script: sudo apt-get update
matrix:
    include:
        - env: fix=no-ec2
          sudo: false
        - env: fix=no-gce
          sudo: required
        - env: fix=no-gce
          sudo: required
          group: deprecated-2017Q4
        - env: fix=precise
          sudo: required
          dist: precise
install: true
notifications:
    email: never
