language: ruby
sudo: false
dist: trusty
install:
    - echo set -e >>file.sh
    - echo about to execute false >>file.sh
    - echo false >>file.sh
    - echo executed false >>file.sh
script:
    - source file.sh
notifications:
    email: never
