language: minimal
matrix:
    include:
        - env: test=osx
          os: osx
          osx_image: xcode7.3
        - env: test=container
          dist: trusty
          sudo: false
        - env: test=sudo-nofilter
          dist: trusty
          sudo: required
script:
    - echo a line to stdout 
    - echo a line to stderr >&2
    - ps -jef --forest
    - ls -l /dev/fd
notifications:
    email: never
