language: ruby
script: awk 'BEGIN{for(i=1;i<=3000;i++)a=a"\naaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";print a; print a >"/dev/stderr"}'
matrix:
    include:
        - env: image=ec2
          sudo: false
        - env: image=gce
          sudo: required
        - env: fix=no-osx
          osx_image: xcode8.3
env:
- run=1
- run=2
- run=3
- run=4
- run=5

install: true
notifications:
    email: never
